language: java
before_install:
  # Install ia32-libs (necessary for Android SDK to run on 64-bit linux)
  # - sudo apt-get clean && sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # Install Android SDK
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  - ls
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android list sdk
  - android update sdk --filter 1,2,3,4,extra --no-ui --force
  - ls ${ANDROID_HOME}/platforms
  # download volley
  - git clone https://android.googlesource.com/platform/frameworks/volley
  - ls
  # Make build.xml
  - android update project --path ./android-sdk-linux/extras/android/support/v7/appcompat/ --target android-17
  - android update project --path ./volley --target android-17
  - android update project --path ./OSMonitor --target android-17
  - cd ./OSMonitor

script:
  - ant clean debug
